services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    command: ["start-dev"]
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: passwd
    ports:
      - 8990:8080