logging:
  level:
    root: ${LOG_LEVEL_ROOT:debug}

server:
  port: 8991

spring:
  application:
    name: gateway
  cloud:
    config:
      enabled: false
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: backend-service
          uri: ${BND_SRV_URL:http://localhost:8992}
          predicates:
            - Path=/backend/**
        - id: client-service
          uri: ${CLI_SRV_URL:http://localhost:8993}
          predicates:
            - Path=/client/**
  security:
    oauth2:
      client:
        provider:
          kc:
            issuer-uri: ${KC_ISSUER_URL:http://localhost:8990/realms/spring-gw-oauth2}
            user-name-attribute: ${KC_ISSUER_NAME:spring-gw-oauth2-provider}
        registration:
            spring-gw-oauth2-client:
              authorization-grant-type: authorization_code
              client-id: spring-gw-oauth2-client
              client-secret: ${KC_CLI1_SECRET}
              provider: kc
              scope: openid
      resourceserver:
        jwt:
          jwk-set-uri: ${KC_JWKS:http://localhost:8990/realms/spring-gw-oauth2/protocol/openid-connect/certs}
